apiVersion: v2
name: tailscale-subnet-router
description: Deploy a Tailscale subnet router on Kubernetes
type: application
version: "1.90.8"
appVersion: "v1.90.8"
home: https://github.com/tolkonepiu/helm-charts
sources:
  - https://github.com/tolkonepiu/helm-charts/tree/main/charts/tailscale-subnet-router
maintainers:
  - name: tolkonepiu
    email: me@popov.wtf
    url: https://popov.wtf
